version: '3'

services:
    postgres:
        container_name: postgres
        image: "postgres"
        environment:
            POSTGRES_PASSWORD: "123"
            POSTGRES_USER: "postgres"
            POSTGRES_DB: "rinha"
        ports:
            - "5432:5432"
        volumes:
            - ./.dbdata:/var/lib/postgresql/data:rw
            - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
            - default
        deploy:
            resources:
                limits:
                    cpus: "1"
                    memory: "400MB"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 5
        restart: always


    api01: &api01
        container_name: api01
        hostname: api01
        environment:
            GIN_MODE: "release"
            DNS: "user=postgres password=123 host=postgres port=5432 dbname=rinha sslmode=disable pool_max_conns=200"
        build:
            context: .
            target: final
        volumes:
            - ./scripts/wait-for-it.sh:/scripts/wait-for-it.sh
        networks:
            - default
        image: api01
        ports:
            - "8081:8080"
        deploy:
            resources:
                limits:
                    cpus: "0.2"
                    memory: "65MB"
        ulimits:
            nproc: 1000000
            nofile:
                soft: 1000000
                hard: 1000000
        depends_on:
            postgres:
                condition: service_healthy
        restart: always

    api02:
        <<: *api01
        container_name: api02
        hostname: api02
        ports:
            - "8082:8080"

    nginx:
        image: nginx:latest
        volumes:
            - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - api01
            - api02
        ports:
            - "9999:9999"
        deploy:
            resources:
                limits:
                    cpus: "0.1"
                    memory: "20MB"
        networks:
            - default

networks:
  default:
    driver: bridge
    name: rinha-2024q1
